/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardGrid: typeof import("ant-design-vue/es")["CardGrid"]
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACarousel: typeof import("ant-design-vue/es")["Carousel"]
    ACheckbox: typeof import("ant-design-vue/es")["Checkbox"]
    ACheckboxGroup: typeof import("ant-design-vue/es")["CheckboxGroup"]
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import("ant-design-vue/es")["Drawer"]
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import("ant-design-vue/es")["Form"]
    AFormItem: typeof import("ant-design-vue/es")["FormItem"]
    AInput: typeof import("ant-design-vue/es")["Input"]
    AInputPassword: typeof import("ant-design-vue/es")["InputPassword"]
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutHeader: typeof import("ant-design-vue/es")["LayoutHeader"]
    ALoader: typeof import('./src/components/ALoader.vue')['default']
    AmountSelector: typeof import('./src/components/AmountSelector.vue')['default']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    ARadio: typeof import("ant-design-vue/es")["Radio"]
    ARadioGroup: typeof import("ant-design-vue/es")["RadioGroup"]
    ASkeleton: typeof import("ant-design-vue/es")["Skeleton"]
    ASkeletonImage: typeof import("ant-design-vue/es")["SkeletonImage"]
    ASpace: typeof import("ant-design-vue/es")["Space"]
    ASpin: typeof import("ant-design-vue/es")["Spin"]
    ATabPane: typeof import("ant-design-vue/es")["TabPane"]
    ATabs: typeof import("ant-design-vue/es")["Tabs"]
    ATag: typeof import("ant-design-vue/es")["Tag"]
    ATextarea: typeof import("ant-design-vue/es")["Textarea"]
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    FilterCheckBoxSelect: typeof import('./src/components/FilterCheckBoxSelect.vue')['default']
    FilterRadioSelect: typeof import('./src/components/FilterRadioSelect.vue')['default']
    OrderCard: typeof import('./src/components/OrderCard.vue')['default']
    OrderStatus: typeof import('./src/components/OrderStatus.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductModifier: typeof import('./src/components/ProductModifier.vue')['default']
    ProductsGrid: typeof import('./src/components/ProductsGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopsGrid: typeof import('./src/components/ShopsGrid.vue')['default']
    SingleProduct: typeof import('./src/components/SingleProduct.vue')['default']
    SingleShop: typeof import('./src/components/SingleShop.vue')['default']
    TheTabBar: typeof import('./src/components/TheTabBar.vue')['default']
  }
}
